//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ПроектИС.
    /// </summary>
    // *** Start programmer edit section *** (ПроектИС CustomAttributes)

    // *** End programmer edit section *** (ПроектИС CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ПроектИС : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private int fБюджет;
        
        private string fСрок;
        
        // *** Start programmer edit section *** (ПроектИС CustomMembers)

        // *** End programmer edit section *** (ПроектИС CustomMembers)

        
        /// <summary>
        /// Бюджет.
        /// </summary>
        // *** Start programmer edit section *** (ПроектИС.Бюджет CustomAttributes)

        // *** End programmer edit section *** (ПроектИС.Бюджет CustomAttributes)
        public virtual int Бюджет
        {
            get
            {
                // *** Start programmer edit section *** (ПроектИС.Бюджет Get start)

                // *** End programmer edit section *** (ПроектИС.Бюджет Get start)
                int result = this.fБюджет;
                // *** Start programmer edit section *** (ПроектИС.Бюджет Get end)

                // *** End programmer edit section *** (ПроектИС.Бюджет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроектИС.Бюджет Set start)

                // *** End programmer edit section *** (ПроектИС.Бюджет Set start)
                this.fБюджет = value;
                // *** Start programmer edit section *** (ПроектИС.Бюджет Set end)

                // *** End programmer edit section *** (ПроектИС.Бюджет Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (ПроектИС.Наименование CustomAttributes)

        // *** End programmer edit section *** (ПроектИС.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (ПроектИС.Наименование Get start)

                // *** End programmer edit section *** (ПроектИС.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (ПроектИС.Наименование Get end)

                // *** End programmer edit section *** (ПроектИС.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроектИС.Наименование Set start)

                // *** End programmer edit section *** (ПроектИС.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (ПроектИС.Наименование Set end)

                // *** End programmer edit section *** (ПроектИС.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Срок.
        /// </summary>
        // *** Start programmer edit section *** (ПроектИС.Срок CustomAttributes)

        // *** End programmer edit section *** (ПроектИС.Срок CustomAttributes)
        [StrLen(255)]
        public virtual string Срок
        {
            get
            {
                // *** Start programmer edit section *** (ПроектИС.Срок Get start)

                // *** End programmer edit section *** (ПроектИС.Срок Get start)
                string result = this.fСрок;
                // *** Start programmer edit section *** (ПроектИС.Срок Get end)

                // *** End programmer edit section *** (ПроектИС.Срок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПроектИС.Срок Set start)

                // *** End programmer edit section *** (ПроектИС.Срок Set start)
                this.fСрок = value;
                // *** Start programmer edit section *** (ПроектИС.Срок Set end)

                // *** End programmer edit section *** (ПроектИС.Срок Set end)
            }
        }
    }
}
