//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Участник.
    /// </summary>
    // *** Start programmer edit section *** (Участник CustomAttributes)

    // *** End programmer edit section *** (Участник CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Участник : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private IIS.Proekt.Роли fРоль;
        
        // *** Start programmer edit section *** (Участник CustomMembers)

        // *** End programmer edit section *** (Участник CustomMembers)

        
        /// <summary>
        /// Роль.
        /// </summary>
        // *** Start programmer edit section *** (Участник.Роль CustomAttributes)

        // *** End programmer edit section *** (Участник.Роль CustomAttributes)
        public virtual IIS.Proekt.Роли Роль
        {
            get
            {
                // *** Start programmer edit section *** (Участник.Роль Get start)

                // *** End programmer edit section *** (Участник.Роль Get start)
                IIS.Proekt.Роли result = this.fРоль;
                // *** Start programmer edit section *** (Участник.Роль Get end)

                // *** End programmer edit section *** (Участник.Роль Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Участник.Роль Set start)

                // *** End programmer edit section *** (Участник.Роль Set start)
                this.fРоль = value;
                // *** Start programmer edit section *** (Участник.Роль Set end)

                // *** End programmer edit section *** (Участник.Роль Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Участник.ФИО CustomAttributes)

        // *** End programmer edit section *** (Участник.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Участник.ФИО Get start)

                // *** End programmer edit section *** (Участник.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Участник.ФИО Get end)

                // *** End programmer edit section *** (Участник.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Участник.ФИО Set start)

                // *** End programmer edit section *** (Участник.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Участник.ФИО Set end)

                // *** End programmer edit section *** (Участник.ФИО Set end)
            }
        }
    }
}
